### ISSUE TITLE
rake radiant:extensions:member:migrate dumps

### ISSUE THREAD

**Issue by wdiechmann** [ihoka-me/radiant-member-extension#3]
Hi,

I'm looking forward so much to using your member extension - but when I run the rake task - it complains like this:

```
$ rake radiant:extensions:member:migrate
(in /Users/walther/Documents/RailsProjects/fmicms)
rake aborted!
undefined method `nav' for #<Radiant::AdminUI:0x2401260>
```

**Comment by wdiechmann** [comment]
I should add that I'm on Radiant 0.8.1 and Rails 2.3.5 :)

And I did 'git' the auto_complete, will_paginate and fastercsv

**Comment by ihoka** [comment]
You should checkout the 0.8 branch (http://github.com/Aissac/radiant-member-extension/tree/0.8) of the extension if you are using Radiant 0.8. Master is only working for Radiant 0.9.

**Comment by wdiechmann** [comment]
exchanged the admin.nav with admin.tab - Radiant 0.8.1 style - but that only lead to errors in the admin/pages view :(
- will have to drop this all together

**Comment by wdiechmann** [comment]
Hi ihoka :)

so good of you to chip in! Will do,

thanx a bunch
